### PR TITLE
feat: make templ fmt, format writen go code in templates

### PR DESCRIPTION
**Pull request by gungun974**
This PR solves the problem as written in the Issue #208 that `go templ` formats Go code which can be written alongside the `templ` keyword.

I'm still new to the go ecosystem but saw what was done in PR #102 with the `go/format` package. 
I think my little modification to format the code with this package when generating the clean string version is good.

Of course I'm open to any improvement.

### CODE REVIEW

**Comment by a-h** [comment]
Hey, this looks great. I noticed this the other day, but hadn't had a chance to look into it.

I would like to see a unit test of the behaviour so that we don't accidentally remove this feature and break it in the future.

It shouldn't be much effort to that, just need to write some badly formatted Go code and check that it gets properly indented, some invalid Go code to show that it is left as-is, and some already well formatted Go code to show that it's not adjusted.

**Comment by jtarchie** [comment]
This may result in not needing `writeIndent` execution and tracking. They could just all just be changed to `Write`.

**Comment by gungun974** [comment]
> This may result in not needing `writeIndent` execution and tracking. They could just all just be changed to `Write`.

I just finish to add unit tests.

If I understand what you said, you propose I write this ? :
```go
func (exp GoExpression) Write(w io.Writer, indent int) error {
	data, err := format.Source([]byte(exp.Expression.Value))
	if err != nil {
		return writeIndent(w, indent, exp.Expression.Value)
	}

	_, err = w.Write(data)
	return err
}
```
If that's it, then you were right, `writeIndent` is more need if we successfully format with the builtin formater !

It's not necessarily obligatory I would say to make this change but I'm still going to make a commit since theoretically it's a performance gain. 

(At least I think so? Afterwards it's not necessarily very important to be a little slower or fast)
​

**Comment by jtarchie** [comment]
I was merely making an observation. I defer to @a-h on what they would want.

**Comment by gungun974** [comment]
> I was merely making an observation. I defer to @a-h on what they would want.

It may have just been an opinion but I actually think it's a good idea. 

The reason I started writing Go was to write simple code in a simple language.

So it seems simpler and faster to me to do a Write directly than to have to apply a function that no longer makes sense.

In addition I want to add but unit tests are also designed to test and refactor things that we didn't think about at the beginning ^^

**Comment by gungun974** [comment]
In any case I'm just going to ask a quick question here on Github since I'm not yet used to contributing that much.

For the small modification I did not want to create an additional commit because it was a fix of a commit which is not part of the main branch. (And also I don't know what message I could write)

So I did a `git rebase` to modify the commit.

This changed the IDs so my commits created everything new. 

To put it on Github I had to `git push force` since I altered the history.

My question is does this kind of thing make sense in a PR or not?
Is it a bad thing ?
Is it more important in a PR to have a clean list of modification with multiple commit or have multiple commit that represent the evolution of the suggestion ? 

In any case I'm just going to ask a quick question here on Github since I'm not yet used to contributing that much.

For the small modification I did not want to create an additional commit because it was a fix of a commit which is not part of the main branch. (And also I don't know what message I could write)

So I did a `git rebase` to modify the commit.

This changed the IDs so my commits created everything new. 

To put it on Github I had to `git push force` since I altered the history.

----

My question is does this kind of thing make sense in a PR or not?
Is it a bad thing ?
Is it more important in a PR to have a clean list of modification with multiple commit or have multiple commit that represent the evolution of the suggestion ? 

I don't think there is one way to think about that and both are valid but I never have the ocasion to just ask.

**Comment by a-h** [comment]
In a PR, you can make as many commits as you like. I find it helpful to see the evolution of the PR.

However, when I merge the PR, I'll "squash" them into a single commit using a "conventional commit" message so that only one single commit is made to the main branch. The commit message history helps to form the release notes, hence standardising them.

* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits
* https://www.conventionalcommits.org/en/v1.0.0/

**Review by a-h — APPROVED** [review]

**Comment by a-h** [comment]
Thanks, that looks great. I've tested it with the LSP and didn't see any issues there.

**Pull request merged**
