### PR TITLE
Warn when using legacy calls

### PR DESCRIPTION
**Pull request by joerdav**

### CODE REVIEW

**Comment by joerdav** [comment]
I've added diagnostics both for LSP and generate command. The templ fmt command also fixes this now.

**Review by a-h — APPROVED** [review]
Looks great!

**Comment by joerdav** [comment]
I'm not sure I understand the errors from the build!

**Comment by a-h** [comment]
I switched to using Nix to build so that I could check that the Nix flake would work.

Since the `go.mod` changed, the hash of deps is different, so it was just a case of updating the `vendorHash` to the latest value. If you set it to an empty string and run the build, it will tell you what the expected version is.

My understanding is that https://github.com/nix-community/gomod2nix is more efficient because it reads the Go module flake lock file, and imports each individual Go module and version into the Nix store, vs the existing implementation which grabs all the deps. Since all the deps for each app are separate, there's no efficient caching in the current version.

I think that gomod2nix will become more standard in Nixpkgs over time, but like all things Nix, it's hard to know.

**Pull request merged**
