### PR TITLE
docs: Generate docs with a static site using templ (rewrite of #401)

### LINKED ISSUE #153: Rebuilding the Docs
Hi 🌊  🐙 !
Hope you are doing well ! First I wanted to thank you for this cool powerful Templating language !! 

I think it would be very cool if we would be transferring the docs to use Templ itself to show the power of it :) ! I would be ready to help with that ! 

Have a nice weekend !

### PR DESCRIPTION
**Pull request by nathan-hello**
Hey there. I forked the repo from @cugu and rewrote much of the go code. The site at https://cugu.github.io/templ/new/ is identical to what this produces. I didn't change any of the frontend. This is a remake from https://github.com/a-h/templ/pull/549 because there was some issues with CI. This closes #153.

Notable changes:
- Broke down files into multiple folders, renamed functions and variables for clarity, reworked how the Page struct is created and used throughout the program. I think it's a more legible program because of these changes. I'm more than happy to go into more detail about the differences, or how the program works as a whole. The output of the html/static files is at `docs/build/`.
- Made the entire project within `docs/` instead of `docgen/`, because I don't see the purpose in keeping around the docusaurus project if this is the direction we're going. This does mean that the lines changes is massive. Most of the deletions (~16k LOC) is just from the docusaurus package-lock.json vs the new package-lock.json which only depends on tailwind and tailwind/typography.
- Added a proper `package.json` for the two dependencies. This also means that there is an `npm run build` alias for running tailwind, running templ, and using the program to build the docs, and a `npm run start` alias for all of that except it also has the --local flag. This also means that `xc docs-run` and `xc docs-build` still works.
- Removed the `_category_.json` files. We get the order from the folder/file name (index.md is always 1). We get the label for folders from the folder name, and for files we get it from the first heading (whatever line that starts with #). The program (at `docs/docs/main.go`) that was generating these files seemed to be out of sync with what was actually there. We can generate the `_category_.json` files again if that's what we want, I would just need to know what the purpose of them are.
- The entrypoint is very simply go run main.go, with an optional flag for `--local` which will build all of the html files and start a localhost:8080 webserver for viewing them.

Notable problems:

- In [using-react-with-templ](https://cugu.github.io/templ/new/syntax-and-usage/using-react-with-templ.html), for example, the chart there doesn't have the right contrast on dark mode. Also some of the text is formatted as red instead of the color pallet the rest of the code blocks use (this is because of the tsx/typescript within the triple-tick, I didn't want to change any of the markdown in this pr because that's not within the scope I think)
- When searching, you can see the markdown formatting. It's a small detail, but I think it should only display the text.
- Clicking on the words on the left triggers the dropdown that displays the relevant articles, but clicking on the actual arrow doesn't.
- While there is a /quick-start/installation.html, if you were to go to /quick-start you get a 404. I would like to make it so that /quick-start/index.html is a page that has a snippet of the pages within it. This is because the Page struct for section pages (read: folders) doesn't actually have any content within it, it just has children which have content.

### CODE REVIEW

**Comment by nathan-hello** [comment]
Any way I could get some feedback/movement on this?

**Comment by a-h** [comment]
Thanks for picking this up!  I haven't had chance to look through because I was focusing on the last release.

I feel like I've gotten back on top of most of the PRs and issues now, and will get to this soon. Sorry to be a blocker here.

**Comment by samueltuyizere** [comment]
This is great @nathan-hello ! For better DX, I'd suggest we add a new script in `docs/package.json`  for dev that can use a combination of [Air](https://github.com/cosmtrek/air) and `templ generate --watch` to have some sort of hot reloading while developing.

**Comment by joerdav** [comment]
I have some xc tasks in this repo for hot-reloading a website: https://github.com/joerdav/shopping-list

**Comment by nathan-hello** [comment]
I tried for a bit to get air to work well and it's really tricky. I suspect that there is an air.toml that makes it work perfectly, but I can't get it there. It seems like it just doesn't care about templ changing the _templ.go files. Maybe because those changes happen so quickly after the initial .templ file being written, but the delay in air.toml is already 0ms. I'm very much okay with dropping air, because most people just want to verify their docs look okay.

I'm not sure what you all do in your templ and tailwind projects, but I am of the opinion that generated code is okay to ignore. It's annoying seeing *_templ.go and style.css be updated by themselves, which seems to happen more often than I would expect. If this is a bad idea for whatever reason, I can unignore them.

**Comment by nathan-hello** [comment]
I'm back. I wanted to get rid of the half-baked air stuff. If someone can get air working, I'll take the pr on my repo. Also, I tried fixing the aforementioned issue with one of the React blurbs and couldn't figure it out. 

I thought I had removed the mini project inside of docs/docs, but I guess not. Again, if there's some reason for them to exist I'd love to know. 

@cugu for my sake in trying to troubleshoot the prism/goldmark stuff with this, could you explain the ideas around the goldmark config? I'm trying to parse how it goes from " ```ts "  to whatever prism.js interprets. In doing so, it seems like the goldmark config has a bunch of stuff that I have no idea what it does.

**Comment by cugu** [comment]
Goldmark converts **```templ** to `<pre><code class="language-templ">`.
Prism.js does syntax highlighting on those blocks.

For the purpose of the other goldmark extensions, their effects should be listed here: https://github.com/yuin/goldmark?tab=readme-ov-file#list-of-extensions

**Comment by joerdav** [comment]
Hey, I'd like to push some changes if that's okay? I think you may have pushes disabled though?

**Comment by nathan-hello** [comment]
> Hey, I'd like to push some changes if that's okay? I think you may have pushes disabled though?

Yeah no problem! I don't think there's a way to allow anyone to push to main (because that would probably be a bad idea), but I will add you as a collaborator and you can do your thing.
 
What things are you changing?

**Comment by joerdav** [comment]
Great thanks, I've just rebased and have introduced HTMX boost for smoother page transitions, there's a few more parts I want to iron out before merge but I think it's close

**Comment by nathan-hello** [comment]
Hey, thanks again for picking this up. I had some nits that I wanted to get out before anything else. If there's an area that I could help with, let me know

**Comment by joerdav** [comment]
Just creating a checklist of my findings so far:

- [ ] Dark mode search results
- [ ] Color scheme to match existing docs site
- [ ] Top bar to match existing site, as we use the same one for https://play.templ.guide/ too
- [ ] Reduce sidebar vertical padding
- [ ] Indent sub-pages in the nav a bit further to create a clearer separation

Post here if you pick any up! Want to avoid us duplicating work.

**Comment by nathan-hello** [comment]
Hey, sorry for the delay. I've been busy with irl stuff, I help with this soon

**Comment by nathan-hello** [comment]
Big highlights: search results are dark moded, prism works with react. 

The templ header you're referring is one that docusaurus makes. That's fine, but it'll be tricky to convert the header from the half-dozen or so CSS classes that make it up into something we can use (tailwind or otherwise).

Prism wasn't downloaded with the react parts, now it is and I put relevant links in the readme.

I refactored `search.js` quite a bit. It's a lot shorter because we're rawdogging html strings instead of the series of function calls to append children/textnodes. Obviously we're sanitizing it (just `<`,`>`, and `&`) and we remove `#` and `\`` so the markdown doesn't bleed into the results page. We can just as easily make it dark mode the way that you had it, but it was really hard to understand (javascript moment) and I didn't see a problem with string templating.

Up next is the rest of the stuff that you mentioned and:
- Search rankings
  - Minimum: "If search is in title, rank highest"
  - Really cool: [TF/IDF](https://naturalnode.github.io/natural/tfidf.html)
- Mermaid diagram (see: /syntax-and-usage/using-react-with-templ.html) doesn't respect dark mode
- Clicking arrow in sidebar doesn't dropdown menu, only clicking word does
- Pages for categories that list all of the pages within them

**Comment by nathan-hello** [comment]
@joerdav 
A couple questions before I touch more stuff:
- How does hx-boost on the body work? Aren't we getting the full page response every time anyways? I don't get why it works.
- Why listen to htmx:beforeOnLoad-type events? They are sending requests for every navigation and I don't see how they're different (in our use-case) from DOMContentLoaded.

**Comment by joerdav** [comment]
> How does hx-boost on the body work?

What hx-boost does is prevent a full page reload, it just takes the response from the new page and replaces the current page with the contents (and replaces the URL) rather than rebuilding the entire DOM.

> Why listen to htmx:beforeOnLoad-type events?

As above the DOM does not reload, that's why we have to use this htmx event instead.

**Comment by nathan-hello** [comment]
Three flickers:

The templ svg would flicker with its alt text until logo.svg was downloaded from /img/logo.svg. I just put the logo.svg in a .templ and now it's baked into the markup, no second download required.

Next was the fact that Prismjs would run alongside the body being presented (because scripts were in <body> with hx-boost). This caused:
- flicker between <pre><code> -> fully fledged prism render 
- templ blocks would not have colors at all until a manual refresh. 

I'm not sure why the second one. I tried adding an event listener for DOMContentLoaded and htmx:load to simply run `Prism.highlightAll()`, but that didn't work. Running the command in the console would work just fine.

The fix for both of these was to remove hx-boost on the body and put the scripts in `<head>`. I know that's what you specifically changed, so sorry for undoing it, but I click around on throttled 3G and in dark mode and I don't see any FOUC or flickering of any kind. If there was some other issue you noticed that hx-boost fixed then I can see what other solutions I can find.

**Comment by nathan-hello** [comment]
FWIW, I just spent two hours trying to get `hx-boost` to work. I thought that I could make it ajax into greatness without a proper http router, but it doesn't seem possible. My idea was to make a folder in `/build/body-only` that was just the `<body>` elements, and hx-boost would swap them in. Then I had to edit the url that htmx would request with a `htmx:requestConfig` event handler, and even then the prism stuff wouldn't run and I couldn't figure out a way to undo the `/body-only/realroute` from the url or the history without littering hx-push-url tags everywhere. Maybe it would be easier to server-render the prism stuff (which would require a node build step) and htmx for real spa-like feel, but for now the scripts being in the head and no boost is what we have. 

Alternatively, if it's in the scope to have a proper http router I could go that route and we could do fancy stuff like this. I've avoided any server-side logic at all because that's what I understood the scope of how you guys run it (github pages afaik).

**Comment by nathan-hello** [comment]
I don't have the time (as made obvious by how long this PR has been open) to make this PR 100%. If anyone wants to pick up on it, I am more than happy to do a little walkthrough and explain stuff. It's a very simple program, so it wouldn't be much. 

I'm closing this PR because if it's taken this long, I'm going to go and come back when I think it's ready with all of @joerdav's feedback. Again, if anyone wants to help or take over this, please make an issue on my fork. 

Not giving up, more apologizing for not having the time to flesh this out as much as I wanted to.

Thanks, I'll be back.

**Pull request closed without merging**
