### PR TITLE
fix: handle slice literals without named types

### LINKED ISSUE #626: parser: Error with slice literal on v0.2.639
This template works with v0.2.598 but returns the following errors with v0.2.639

```
$ templ generate templates/

(✗) Error generating code [ file=/home/angel/go/projects/templ-bug/templates/index.templ error=/home/angel/go/projects/templ-bug/templates/index.templ parsing error: <nav>: expected end tag not present or invalid tag contents: line 25, col 16 ]
(✗) Event handler failed [ error=failed to generate code for "/home/angel/go/projects/templ-bug/templates/index.templ": /home/angel/go/projects/templ-bug/templates/index.templ parsing error: <nav>: expected end tag not present or invalid tag contents: line 25, col 16 ]
(✗) Error [ error=failed to generate code for "/home/angel/go/projects/templ-bug/templates/index.templ": /home/angel/go/projects/templ-bug/templates/index.templ parsing error: <nav>: expected end tag not present or invalid tag contents: line 25, col 16 ]
(✗) Command failed: generation completed with 1 errors
```

```go
package templates

type TabData struct {
	Name string
}

templ tabs(tabs []*TabData) {
    <div>
        for _, tab := range tabs {
            <a href="#none">{ tab.Name }</a>
        }
    </div>
}

templ Index() {
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<title>Chat</title>
		</head>
		<body >
                    <nav>
                        @tabs([]*TabData{
                            {Name: "A"},
                            {Name: "B"},
                        })
                    </nav>
		</body>
	</html>
}
```

Passing an empty slice to tabs doesn't return an error:
```go
                @tabs([]*TabData{})
```

### PR DESCRIPTION
**Pull request by a-h**
Fixes #626

### CODE REVIEW

**Comment by joerdav** [comment]
This all makes complete sense, though I have some test cases that might require some minor changes. Quite niche scenarios too.

```
{
	name: "function call with array of explicit length",
	input: `tabs([2]TabData{
  {Name: "A"},
  {Name: "B"},
})`,
},
{
	name: "function call with array of inferred length",
	input: `tabs([...]TabData{
  {Name: "A"},
  {Name: "B"},
})`,
},
```

**Comment by joerdav** [comment]
Oh! I expected that to fail because of:

`        if ep.Previous == token.LBRACK && tok == token.RBRACK {`

Maybe I need to read the PR again...

**Comment by a-h** [comment]
Those additional cases don't appear to require any changes, because it's hitting the logic that if there's an open `[`, anything until the next `]` is OK.

**Comment by joerdav** [comment]
Cool, racked my brain and can't think of any more scenarios. Re-read the code with a fresh brain, and it all makes sense now.

**Review by joerdav — APPROVED** [review]

**Comment by a-h** [comment]
Thanks for thinking about it, that's half the battle. :)

**Pull request merged**
