### PR TITLE
docs: Add GitHub Actions integration to templ documentation

### PR DESCRIPTION
**Pull request by capthiron**
## Overview

I have developed a GitHub Action named [templ-generator-action](https://github.com/marketplace/actions/templ-generator-action) to enhance the developer experience for those using `templ` in their projects. With this PR, I aim to update the `templ` documentation by adding a subsection under 'Commands and tools' to inform the community about this new integration tool available on the GitHub Marketplace.

## Changes

- Introduced a new subsection titled 'GitHub Action for `templ`', providing details on the features, usage, and benefits of the `templ-generator-action`.
- Included a direct link to the `templ-generator-action` on the GitHub Marketplace, allowing users to easily find and install the action.

## Benefits

- Empowers users with the ability to automate `.templ` file conversions, aligning with modern CI/CD practices.
- Enhances discoverability of `templ`-related tools, fostering a more robust and collaborative community.
- Encourages users to adopt this new tool, which is designed to keep their Go codebase synchronized with `.templ` files effortlessly.

## Motivation

The `templ-generator-action` was created out of a desire to contribute to the `templ` community and to share a tool that I believe will make a positive impact on the development workflows of many. By including this in the official documentation, we can ensure that it reaches a wider audience and provides value to more developers.

## Additional Notes

- All links have been checked for accuracy.
- The content addition is intended to be informative yet succinct, matching the existing style of the documentation.

I am excited to share the `templ-generator-action` with the community and am open to any feedback or suggestions for further enhancements. Thank you for considering this addition to the `templ` documentation.

### CODE REVIEW

**Comment by a-h** [comment]
Thanks for your work on this!

Personally, I avoid the use of custom actions in GitHub and prefer to use raw command line tools where possible. This is because debugging the action can be a pain, as can testing locally, even with tools like Act.

I don't think there are any docs that describe a typical CI workflow with templ, so there's definitely a gap for something, even if it's not exactly this!

My other thought is that use of a GitHub Actions is security impacting, since it can run arbitrary code, gain access to secrets etc. if your GitHub account was compromised or deleted, it could affect many users.

Just a thought, but would you be up for transferring the action to the templ-go organisation, and becoming a maintainer of that within the organisation?

Aside from that, we (as a community) probably need to discuss the concept of whether we want/need a GitHub action.

From my perspective, I think it's likely to bring awkward support requests, so I'm not sure I'd want to take it on...

I'll mention this PR on the Slack channel to get more feedback.

**Comment by joerdav** [comment]
I agree, it makes more sense for actions to use templ commands directly. My main reasoning for that is that everyones workflows seem to be different, some generate their templ locally and commit it, allowing the CI only to validate that they have been generated properly. Others add generated go code to .gitignore files and solely allow templ generate to run as part of the build process.

I think with templ being simple to install the best use of the docs would be a small example of how to install templ on a GHA runner.

**Comment by alehechka** [comment]
I'd agree with the above comments. The action itself that you put together is simple enough and includes some commands that devs likely already have in their own workflows (i.e. setup-go and installing templ) that they wouldn't gain much from abstracting that away. 

Additionally, workflows can vary greatly. My personal preference is, like @joerdav mentioned, to .gitignore all `*_templ.go` files and generate them all during the build completely inside a docker container. As for formatting `*.templ` files, I use VSCode with formatOnSave enabled so my files are always formatted before I commit.

I think it's valid to keep the action as a personal project, but I don't think I would advocate for the templ organization taking on its maintenance or official support.

**Comment by alehechka** [comment]
As for the installation of `templ`, I found it tedious to keep other references to it in sync with my `go.mod` file so I've been using this command which grabs the exact version that the project is using.

```shell
        go install github.com/a-h/templ/cmd/templ@$(go list -m -f '{{ .Version }}' github.com/a-h/templ)
```

**Comment by joerdav** [comment]
> go install github.com/a-h/templ/cmd/templ@$(go list -m -f '{{ .Version }}' github.com/a-h/templ)

That's cool @alehechka

**Comment by capthiron** [comment]
Thank you all for the constructive dialogue regarding the GitHub Action I've proposed.

@a-h , I completely understand the concerns about security and the implications of adding a custom action to the official templ-go organization. Your suggestion of transferring the action and becoming a maintainer is an interesting one. I am open to this possibility if the community sees value in it and decides it's a direction we want to take. I am committed to ensuring the security and ease of use of the action, should it become a part of the official templ tools.

@joerdav and @alehechka , I appreciate your points about the range of workflows templ users use. It's clear that flexibility is key when it comes to how developers integrate templ into their processes. The GitHub Action I've developed is intended to complement these processes, not replace them, offering an automated, one-liner option for those who might prefer it.

I believe the best path forward is to open up this discussion to the wider community. If there is a consensus that the GitHub Action would be a beneficial addition to the templ-go organization, I would be more than willing to transfer the repository and take on a maintainer role. If the community decides otherwise, I will happily continue to support the action independently.

Ultimately, my goal is to contribute to the templ community in a way that is aligned with the collective vision and enhances the developer experience. I look forward to hearing more from the community and am prepared to follow through on whichever decision is reached.

Thank you again for considering this integration and for the opportunity to contribute to the community's toolset.

**Pull request closed without merging**
