### PR TITLE
docs: link to tree-sitter-templ for Neovim

### PR DESCRIPTION
**Pull request by vrischmann**
Hi,

I've been working on a tree-sitter parser lately for Templ (see [tree-sitter-templ](https://github.com/vrischmann/tree-sitter-templ)), which works quite well right now. Here are some screenshots

image
image

One area where it's quite good compared to templ.vim is highlighting Go code because I was able to reuse the Go tree-sitter [parser](https://github.com/tree-sitter/tree-sitter-go) for some things. 
Some other things don't work well yet (conditional attributes for example).

With this PR I'm proposing adding a link to [tree-sitter-templ](https://github.com/vrischmann/tree-sitter-templ) in the documentation page "IDE support", I believe it could be useful to others.

### CODE REVIEW

**Comment by vrischmann** [comment]
> Nice! I've installed this, the nodes show up when I run tree sitter playground and TSNodeUnderCursor, however when I run TSHighlightCapturesUnderCursor, I get nothing. So it results in no colors?

I'm assuming you're talking about this ? https://github.com/nvim-treesitter/playground
I didn't know this existed, seems like it would have been helpful while working on the grammar :smile: 
I'll check it out later.

> So it results in no colors?
What do `:checkhealth` and `:InspectTree` say ?

**Comment by joerdav** [comment]
Doesn't look good actually!
```
Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - templ               . . . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

```

The tree looks normal though, I think:
image

**Comment by joerdav** [comment]
That did it! The answer was RTFM :) Thanks

**Review by a-h — APPROVED** [review]

**Comment by a-h** [comment]
Thanks for your work on this @vrischmann - maybe you and @joerdav could join forces!

**Comment by vrischmann** [comment]
Yeah, I'd be happy to take any contribution I can get :smile: 
Thanks for the merge !

**Pull request merged**
