### PR TITLE
docs: add more testing guidance

### PR DESCRIPTION
**Pull request by michaelByrne**
Integrated and adapted Adrian's [testing post](https://adrianhesketh.com/2021/10/17/testing-templ-html-rendering-with-goquery/) into the docs

### CODE REVIEW

**Comment by a-h** [comment]
Thanks for that!

**Comment by michaelByrne** [comment]
> Thanks for that!

glad to help. any other issues or tasks you think would be good for me to work on? as somewhat of a newbie to the repo

**Comment by a-h** [comment]
Thanks! If you're up for another docs change, yesterday, we added support for function calls in string attribute expressions, but there's no documentation for it at https://templ.guide/syntax-and-usage/attributes#string-expression-attributes

We try to keep the issues labelled appropriately - to identify stuff we need to think about, discuss, and label stuff that we think is OK to pick up.

However, I think we might do well to start running a regular planning session, like the Go team does with proposals, e.g. https://github.com/golang/go/issues/33502#issuecomment-1973634667

**Comment by michaelByrne** [comment]
> Thanks! If you're up for another docs change, yesterday, we added support for function calls in string attribute expressions, but there's no documentation for it at https://templ.guide/syntax-and-usage/attributes#string-expression-attributes
> 
> We try to keep the issues labelled appropriately - to identify stuff we need to think about, discuss, and label stuff that we think is OK to pick up.
> 
> However, I think we might do well to start running a regular planning session, like the Go team does with proposals, e.g. [golang/go#33502 (comment)](https://github.com/golang/go/issues/33502#issuecomment-1973634667)

yeah, i can do that for sure! and i'd be down to join planning sessions as well

**Pull request merged**
