### PR TITLE
feat: support void element parsing, fixes #637

### LINKED ISSUE #637: parser: Unclosed void tags (like input/image) break generation
Hello maintainers,

I just happened to come across a series of reuses of HTML Templates inside of templ and one thing jumping at me was that templ expects all tags to be closed, even if they are so called "void" like input or image or else (https://html.spec.whatwg.org/multipage/syntax.html#start-tags).

I didn't find an open issue to this so I hope it's ok to bring this up. 

Is the support of unclosed tags i.e. `<image src="my-image.png">` something that could make templ more HTML5 alike?

### PR DESCRIPTION
**Pull request by a-h**

### CODE REVIEW

**Comment by bastianwegge** [comment]
LGTM 🎉

**Review by joerdav — APPROVED** [review]
This looks great to me, glad to see the diagnoser coming in handy again! 
On thing I spotted, feel free to merge without as it is fine without, Is that rather than adding to the TestFormatter test you could add to the other formatter tests: 
https://github.com/a-h/templ/tree/main/parser/v2/testdata

To be honest we could probably remove that test entirely, I find the txt files easier to add than the table tests.

**Comment by a-h** [comment]
I've migrated the tests to the txtar format.

**Comment by joerdav** [comment]
I hope you wrote a script to do that for you lol!

**Comment by a-h** [comment]
I did! 😂

**Pull request merged**
