### PR TITLE
Update LICENSE, fix copyright license year

### PR DESCRIPTION
**Pull request by JasonnnW3000**
Yearly copyright bump. Padding my changed LOC! 😛

### CODE REVIEW

**Comment by a-h** [comment]
Looks like a bot account, presumably to build a credible looking account.

**Comment by JasonnnW3000** [comment]
No, this account not a bot , I do it for fun and to add my changed  LOC

**Comment by a-h** [comment]
OK. When you create a Github account, don't create any source repos or write any code, then do a bunch of trivial PRs to a large number of repos, it makes you look like an attacker - read up on the xz backdoor and "jia tan" as to why!

**Comment by JasonnnW3000** [comment]
Understood, thank you for your suggestion! Happy New Year!

**Comment by reneroth** [comment]
> No, this account not a bot , I do it for fun and to add my changed LOC

What you are doing is worse than worthless, it's actively harming the repo owners who merge your changes in.  
You are not FIXING the copyright year, you are BREAKING it. The copyright year is the year of first publication! Copyright protection STARTS WITH PUBLICATION — by changing this year, you give the works LESS protection.

JFC, before you go opening over _one thousand PRs_, at least try understanding what the fuck you're doing. First thing I'm doing this year is clearing my mailbox of your spam PRs.

**Pull request closed without merging**
