### PR TITLE
fix(lsp): update URI handling for non-templ files for references

### LINKED ISSUE #893: bug: go to definition causes error in Neovim v0.10.x
## Description

When using the "Go to Definition" feature in Neovim with templ components, an error occurs specifically for the `@atoms.Input` component. This error doesn't happen for other components or when the file containing the `Input` component is already open. Importantly, this issue does not occur in Visual Studio Code, suggesting it might be specific to the Neovim integration.

## Code Example

WaitlistForm component:
```go
package organisms
import (
	"github.com/axzilla/goilerplate/components/atoms"
	"github.com/axzilla/goilerplate/forms"
)
templ WaitlistForm(values forms.Waitlist, errors map[string]string) {
	<form hx-post="/waitlist" class="flex flex-col gap-2 w-96" hx-swap="outerHTML">
		if errors["success"] != "" {
			<div role="success" class="alert border border-primary">
				<div class="flex flex-col gap-2 justify-center items-center text-center font-bold">
					<p>🚀 You're in! 🚀</p>
					<p>Smart move, future SaaS superstar! We'll buzz your inbox when it's time to launch.</p>
				</div>
			</div>
		}
		@atoms.Input(templ.Attributes{
			"value":       values.Email,
			"name":        "email",
			"placeholder": "Email",
		}, "", errors["email"])
		<button data-loading-disable type="submit" class="btn btn-primary">Let's Go</button>
	</form>
}
```

Input component:
```go
package atoms
templ Input(attrs templ.Attributes, label, err string) {
	<div class="flex flex-col gap-2">
		if label != "" {
			<p class="">{ label }</p>
		}
		<input { attrs... } class="input input-bordered"/>
		if err != "" {
			<p class="text-red-500">{ err }</p>
		}
	</div>
}
```

## Error Message

When trying to use "Go to Definition" on `@atoms.Input`, the following error occurs:

```
Error executing vim.schedule lua callback: ...ar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/util.lua:1914: index out of range
stack traceback:
	[C]: in function '_str_byteindex_enc'
	...ar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/util.lua:1914: in function 'locations_to_items'
	...eovim/0.10.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:435: in function 'handler'
	.../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

## Environment

- Neovim version: 0.10.1
- templ version: v0.2.747
- Operating System: macOS

## Additional Information

- The error only occurs for the `@atoms.Input` component in Neovim.
- "Go to Definition" works for other components in Neovim.
- The error doesn't occur if the file containing the `Input` component is already open in Neovim.
- This issue does not occur in Visual Studio Code, where "Go to Definition" works as expected.
- A minimal Neovim configuration has been tested, and the issue persists.

## Expected Behavior

"Go to Definition" should successfully navigate to the definition of the `Input` component without throwing an error, as it does in Visual Studio Code.

## Questions

1. Is there an error in the provided code that could be causing this issue?
2. Are there any known incompatibilities between templ and Neovim 0.10.1?
3. Could this be related to how the templ language server is interacting with Neovim's LSP client?

Any insights or suggestions for troubleshooting would be greatly appreciated. Thank you for your time and effort in addressing this issue.

### PR DESCRIPTION
**Pull request by tris203**
Closes #893 

This took far too long to find but seems to resolve the issue for me

### CODE REVIEW

**Comment by tris203** [comment]
Perhaps a more elegant solution is for the function that concerts the range to return a uri too?

**Comment by tris203** [comment]
I think this is ready for a review

**Comment by joerdav** [comment]
Great thanks so much for the contribution! I will test this out, I also think that this could benefit from an additional test in https://github.com/a-h/templ/blob/main/cmd/templ/lspcmd/lsp_test.go if you have time? @a-h has built a nice test framework for unit testing the LSP.

If you don't have time let me know and I can pick that up.

**Comment by tris203** [comment]
> Great thanks so much for the contribution! I will test this out, I also think that this could benefit from an additional test in [`main`/cmd/templ/lspcmd/lsp_test.go](https://github.com/a-h/templ/blob/main/cmd/templ/lspcmd/lsp_test.go?rgh-link-date=2024-09-06T10%3A04%3A19Z) if you have time? @a-h has built a nice test framework for unit testing the LSP.
> 
> If you don't have time let me know and I can pick that up.

I have added a test @joerdav 
I tried to integrate it in the same style as the others, let me know if there is anything you want changed

**Comment by joerdav** [comment]
I've just added one more for a reference within a templ file, but now I think this is good to go. Thanks for the contribution!

**Pull request merged**
