### PR TITLE
Content-Enconding gzip support for the hot reloader proxy

### PR DESCRIPTION
**Pull request by JamesTiberiusKirk**
**Context:**
IMO the hot reloader proxy feature deserves to be a whole different cli tool, and after figuring out that this feature did not work for me (while using echo router) I decided to implement this myself. 
During the implemnetation I encountered the same issue I was having with the built in templ one, which is the script tag injector just not injecting anything. 
I figured out why and here is the PR to fix it for templ.

I have not seen any contribution docs so please, direct me to them if ive missed them or let me know what else there would need to be done for this work to get merged in.

**Work:** 
The work itself is quite self explanatory, its just checking to see if the body is `gzip` encoded and decodes it and re-encodes if it is.
This should also make it quite easy to add more encodings in the future if needed.

### CODE REVIEW

**Review by a-h — APPROVED** [review]

**Comment by a-h** [comment]
Great job, thanks for that.

There's a contributing guide at https://github.com/a-h/templ/blob/main/CONTRIBUTING.md but nothing really relevant in there for this change.

A unit test would be good if you have time to revisit this - the proxy is currently tested via an integration test that runs the `--watch` feature, and this new `gzip` behaviour isn't covered by it.

**Comment by yardenshoham** [comment]
I think I'm hitting this bug because I am using the echo router with gzip as well. When I hit Ctrl+C it starts another web process and keeps it running in the background:

```shell
$ templ generate --watch --proxy="http://localhost:1998" --cmd="go run ."
Processing path: /home/yarden/my-app
Generating dev code: /home/yarden/my-app
(✓) Generated code for "/home/yarden/my-app/components/components.templ" in 5.1171ms
(✓) Generated code for 1 templates with 0 errors in 5.3993ms
Executing command: go run .
Proxying from http://127.0.0.1:7331 to target: http://localhost:1998
Opening URL: http://localhost:1998
Server not ready. Retrying in 358.439489ms...
Server not ready. Retrying in 770.302868ms...
2024/02/21 09:42:08 Querying app labels on http://api.local:32094
⇨ http server started on [::]:1998
Server not ready. Retrying in 1.401432211s...
time=2024-02-21T09:42:10+02:00 method=GET uri=/ status=301 latency=176.3µs
time=2024-02-21T09:42:10+02:00 method=GET uri=/sb status=200 latency=2.9226ms
time=2024-02-21T09:42:12+02:00 method=GET uri=/ status=301 latency=908.6µs
time=2024-02-21T09:42:12+02:00 method=GET uri=/sb status=200 latency=4.3037ms
time=2024-02-21T09:42:12+02:00 method=GET uri=/sb/assets/css/tom-select.css status=200 latency=2.9967ms
time=2024-02-21T09:42:12+02:00 method=GET uri=/sb/assets/js/htmx.min.js status=200 latency=13.1111ms
time=2024-02-21T09:42:12+02:00 method=GET uri=/sb/assets/css/bulma.min.css status=200 latency=27.2455ms
time=2024-02-21T09:42:12+02:00 method=GET uri=/sb/assets/js/tom-select.popular.min.js status=200 latency=8.3962ms
time=2024-02-21T09:42:13+02:00 method=GET uri=/favicon.ico status=404 latency=121.6µs
Proxy to target error: http: proxy error: max retries reached
Proxy to target error: http: proxy error: max retries reached
Proxy to target error: http: proxy error: max retries reached
now i will exit^CStopping...
Generating production code: /home/yarden/my-app
(!) Deleted file "/home/yarden/my-app/components/components_templ.txt"
(✓) Generated code for "/home/yarden/my-app/components/components.templ" in 5.5091ms
(✓) Generated code for 1 templates with 0 errors in 5.7483ms
Executing command: go run .
⇨ http server started on [::]:1998
2024/02/21 09:42:55 Querying app labels on http://api.local:32094

$ sudo lsof -ti:1998
29989
$ time=2024-02-21T09:47:26+02:00 method=GET uri=/sb status=200 latency=1.8122ms
time=2024-02-21T09:47:26+02:00 method=GET uri=/sb/assets/css/bulma.min.css status=304 latency=250.4µs
time=2024-02-21T09:47:26+02:00 method=GET uri=/sb/assets/css/tom-select.css status=304 latency=200.7µs
time=2024-02-21T09:47:26+02:00 method=GET uri=/sb/assets/js/tom-select.popular.min.js status=304 latency=120.6µs
```

**Comment by yardenshoham** [comment]
Nevermind I guess it's https://github.com/a-h/templ/issues/487

**Comment by a-h** [comment]
Yup, that's right. I'm just finishing off some fuzzing tests to test a new parser feature, and I'll ship a new release. Won't be long now.

**Pull request merged**
